spring.datasource.url=jdbc:mysql://ballast.proxy.rlwy.net:48337/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rpFAzKuGzGemQMXNsTwGLTLKXsVBKNHg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.servlet.context-path=/api
#```
#
#Railway pe **Variables** mein ye add karo:
#```
#SPRING_PROFILES_ACTIVE = prod